#!/usr/bin/env python3
import argparse, logging, json, re, sys

from os.path import isfile, dirname, abspath
from os import makedirs
from time import sleep
from datetime import datetime

from enum import Enum, auto
from typing import Union, Tuple, List

from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

from bs4 import BeautifulSoup

import requests, telegram

parser = argparse.ArgumentParser(description="JOBO BOT")
parser.add_argument('--prod', dest='prod', action='store_true',
        help='Production mode (testing is the default mode)')
parser.add_argument('--conf', dest='conf', type=str,
        help='Config file')
args = parser.parse_args()

test = not args.prod
config_file = 'config.json' if not args.conf else args.conf

# Load config
conf = None
try:
    with open(config_file) as f:
        conf = json.load(f)
        conf = conf['prod'] if args.prod else conf['test']
except FileNotFoundError:
    print(f"No se ha encontrado el fichero de configuración {config_file}.")
    sys.exit(1)

# Setup logger
logger = logging.getLogger("jobo_bot")

logger.setLevel(logging.DEBUG if test else logging.INFO)
formatter = logging.Formatter('%(asctime)s:%(levelname)s:%(process)d:%(message)s')
log_file = 'jobo_bot.test.log' if test else 'jobo_bot.log'

try:
    file_handler = logging.FileHandler(log_file)
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)
except OSError as e:
    print("WARNING: Error setting up file logger: ", e)
    pass

stream_handler = logging.StreamHandler(sys.stdout)
stream_handler.setFormatter(formatter)
logger.addHandler(stream_handler)

# Create database path if not exists
db_path = dirname(abspath(conf["db_file"]))
try:
    makedirs(db_path)
except FileExistsError:
    pass
else:
    logger.debug(f"Created db directory: {db_path}")

Base = declarative_base()

def escape_md(text:str):
    if text is None:
        return text
    for char in "_*[]()~`>#+-=|{}.!":
        text = text.replace(char, '\\'+char)
    return text

class Event(Base):
    __tablename__ = 'events'

    id = Column(Integer, primary_key=True)
    title = Column(String, nullable=False)
    date = Column(String)
    duration = Column(String)
    place = Column(String)
    info_url = Column(String)
    buy_url = Column(String)
    img_url = Column(String)
    message_id = Column(String)

    def __repr__(self):
        return f"<Event id='{self.id}' title='{self.title}' date='{self.date}' message_id='{self.message_id}'>"

    @property
    def message_md(self):
        message = f"*{escape_md(self.title)}*"
        if self.place:
            message += f" \\- {escape_md(self.place)}"
        message += "\n"
        message += f"_{escape_md(self.date)}_\n"
        if self.info_url:
            if self.info_url == self.buy_url:
                message += f"[Mas información / Comprar entradas]({self.info_url})\\."
            else:
                message += f"[Mas información]({self.info_url})"
        if self.buy_url and self.buy_url != self.info_url:
            if self.info_url:
                message += "\\. "
            message += f"[Comprar entradas]({self.buy_url})\\."
        if self.info_url or self.buy_url:
            message += "\n"
        return message

def get_event(session, title, date):
    return session\
            .query(Event)\
            .order_by(Event.id.desc())\
            .filter(Event.title == title, Event.date == date).first()

def get_or_create_event(session, data):
    event = get_event(session, data["title"], data["date"])
    if not event:
        event = Event(**data)
    return event

def get_non_sent_events(session):
    return session\
            .query(Event)\
            .order_by(Event.id.desc())\
            .filter(Event.message_id == None).all()

msg_send_count = 0

def wait_send():
    global msg_send_count
    sleep(1.05)
    msg_send_count += 1
    if msg_send_count % 20 == 0:
        sleep(40) # Avoid sending more than 20 messages per minute

def notify_error(msg:str, escape=True):
    bot = telegram.Bot(token=conf["telegram_bot_token"])
    kwargs = {
            "chat_id": conf["telegram_chat_id"],
            "parse_mode": telegram.ParseMode.MARKDOWN_V2,
            "text": escape_md(msg) if escape else msg,
            }
    try:
        bot.send_message(**kwargs)
    except:
        logger.error("SENDING ERROR MESSAGE VIA TELEGRAM")
    else:
        wait_send()

def url_normalize_slashes(url): # copied from https://stackoverflow.com/a/33322084/4439906
    url = str(url)
    segments = url.split('/')
    correct_segments = []
    for segment in segments:
        if segment != '':
            correct_segments.append(segment)
    first_segment = str(correct_segments[0])
    if first_segment.find('http') == -1:
        correct_segments = ['http:'] + correct_segments
    correct_segments[0] = correct_segments[0] + '/'
    normalized_url = '/'.join(correct_segments)
    return normalized_url

def notify_new_event(event: Event):
    bot = telegram.Bot(token=conf["telegram_bot_token"])
    send_conf = {
            "chat_id": conf["telegram_chat_id"],
            "parse_mode": telegram.ParseMode.MARKDOWN_V2,
            }
    message = None
    send_image = bool(event.img_url)
    if send_image:
        img_url = url_normalize_slashes(event.img_url)
        try:
            message = bot.send_photo(photo = img_url, caption = event.message_md, **send_conf)
        except telegram.error.BadRequest: #TODO: fix image errors
            logger.error(f"SENDING IMAGE FOR {event}. RETRYING WITHOUT IMAGE!")
            send_image = False
    if not send_image:
        try:
            message = bot.send_message(text=event.message_md, **send_conf)
        except telegram.error.BadRequest as e:
            logger.error(f"SENDING {event}: {repr(e)}")
            notify_error(f"*ERROR SENDING {escape_md(str(event))}:*\n {escape_md(repr(e))}", False)
    if message:
        event.message_id = message.message_id
        logger.info(f"Message sent: {event}")
        wait_send()

def update_event_info(event): #TODO: fix, test and use this function
    global msg_send_count
    bot = telegram.Bot(token=conf["telegram_bot_token"])
    assert event.message_id is not None
    kwargs = {
            "chat_id": conf["telegram_chat_id"],
            "message_id": event.message_id,
            "parse_mode": telegram.ParseMode.MARKDOWN_V2,
            "caption" if event.img_url else "text": event.message_md,
            }
    try:
        bot.edit_message_caption(photo = event.img_url, **kwargs)\
                        if event.img_url\
                        else bot.edit_message_text(**kwargs)
    except telegram.error.BadRequest as e:
        logger.error(f"UPDATING MESSAGE {event}: {repr(e)}")
        notify_error(f"*ERROR UPDATING MESSAGE {escape_md(str(event))}:*\n {escape_md(repr(e))}", False)
    else:
        wait_send()


MD_BASE_URL   = "https://tienda.madrid-destino.com/es/"
MD_API_ENDPOINT = "https://api2-tienda.madrid-destino.com/public_api/organizations"
MD_API_HEADERS = { "x-salechannel" : "3c4b1c81-e854-4324-830f-d59bec8cf9a2" }

# Exclude non jobo and future events
def md_event_filter(event):
    valid_from = datetime.strptime(event["validFrom"], '%Y-%m-%d %H:%M:%S')
    # is_valid = valid_from <= datetime.now() if valid_from else True
    is_valid = True
    is_jobo = "JOBO" in event["enabledMembershipNames"] or event["joboMembership"]
    return is_jobo and is_valid

# def getDescription(event_metas):
#     for meta in event_metas:
#         if meta["name"] == "description":
#             return meta["content"]
#     return None

def MadridDestinoGetter(session) -> List[Event]:
    logger.debug("Starting MadridDestinoGetter")
    try:
        response = requests.get(MD_API_ENDPOINT, headers=MD_API_HEADERS)
        data = response.json()["data"]
    except Exception as e:
        print("Exception:", e)
        return []
    else:
        events = []
        for place in data:
            for event in filter(md_event_filter, place["events"]):
                event_data = {
                        "title": event["title"],
                        "date": event["eventDateRange"],
                        "place": place["name"],
                        "img_url": event["featuredImage"]["url"],
                        "info_url": f'{MD_BASE_URL}{place["slug"]}/{event["slug"]}',
                        # "description": getDescription(event["metas"])
                        }
                ev = get_or_create_event(session, event_data)
                logger.debug(f"Got event: {ev}")
                session.add(ev)
                events.append(ev)
        session.commit()
        return events

class FindMode(Enum):
    RAW=auto()
    BOOL=auto()
    TEXT=auto()
    NORMALIZEDTEXT=auto()
    ATTR=auto()

SE_SELECTORS = {
        "events": "div.group_content > ul > li > .product",
        "title": ".title",
        "date": ".date .unique, .date .range",
        "place": ".location .site",
        "img_url": "img",
        "info_url": ".more_info a",
        "buy_url": "span.button a",
        }

SE_EVENT_DATA_SELECTORS = {
        "title": FindMode.NORMALIZEDTEXT,
        "date": FindMode.NORMALIZEDTEXT,
        "place": FindMode.NORMALIZEDTEXT,
        "img_url": (FindMode.ATTR, "data-img-large"),
        "info_url": (FindMode.ATTR, "href"),
        "buy_url": (FindMode.ATTR, "href")
        }

SE_BASE_URL   = "https://madridcultura-jobo.shop.secutix.com"
SE_LOGIN_URL  = f"{SE_BASE_URL}/account/login"
SE_EVENTS_URL = f"{SE_BASE_URL}/secured/list/events"

def se_find_selector(raw_data, selector_name, mode: Union[FindMode, Tuple[FindMode, str]] = FindMode.RAW):
    result = None
    try:
        element = raw_data.select(SE_SELECTORS[selector_name])[0]
    except Exception:
        pass
    else:
        if mode == FindMode.RAW:
            result = element
        elif mode == FindMode.BOOL:
            assert False, "Not implemented"
        elif mode == FindMode.TEXT:
            result = element.text
        if mode == FindMode.NORMALIZEDTEXT:
            result = element.text\
                    .replace('\n',' ')\
                    .replace('\r',' ')\
                    .replace('\t',' ')\
                    .strip()
            result = re.sub(r"\s\s+", " ", result)
        elif isinstance(mode,tuple) and mode[0] == FindMode.ATTR:
            assert len(mode) == 2 and isinstance(mode[1], str), "mode should be of form (FindMode.ATTR, str)"
            result = element.get(mode[1])
    return result

def se_find_selectors(raw_data, selectors_with_modes):
    data = {sel: se_find_selector(raw_data, sel, mode) for sel, mode in selectors_with_modes.items()}
    return data

def se_get_token(requests_session):
    logger.debug("Getting csrf token")
    result = requests_session.get(SE_LOGIN_URL)
    soup = BeautifulSoup(result.text, 'html.parser')
    return soup.find('input', {'name': '_csrf'}).get('value')

def se_login(requests_session, token):
        logger.debug("Logging in")
        payload = {
                'login': conf["secutix_user"],
                'password': conf["secutix_password"],
                '_rememberThisLogin': 'on',
                '_csrf': token
                }
        return requests_session.post(
                SE_LOGIN_URL,
                data=payload,
                headers=dict(referer=SE_LOGIN_URL)
                )

def se_parse_event(session, event_raw):
    event_data = se_find_selectors(event_raw, SE_EVENT_DATA_SELECTORS)
    if event_data["buy_url"]: # Si no tiene buy_url es porque están agotadas las entradas
        event_data["buy_url"] = f"{SE_BASE_URL}{event_data['buy_url']}"
        event = get_or_create_event(session, event_data)
        logger.debug(f"Scraped event: {event}")
        return event

def se_parse_events(session, requests_session):
    logger.debug("Scraping secutix.com events")
    html = requests_session.get(
            SE_EVENTS_URL,
            headers = dict(referer=SE_EVENTS_URL)
            ).text
    events_raw = BeautifulSoup(html, 'html.parser').select(SE_SELECTORS["events"])
    logger.debug(f"{len(events_raw)} events found")
    events =  []
    for event_raw in events_raw:
        try:
            event = se_parse_event(session, event_raw)
        except Exception as e:
            logger.error(f"PARSING EVENT: {repr(e)}")
            notify_error(f"*ERROR PARSING EVENT:*\n {escape_md(repr(e))}", False)
        else:
            if event:
                session.add(event)
                events.append(event)
    session.commit()
    return events

def SecutixScraper(session):
    logger.debug("Starting SecutixScraper")
    requests_session = requests.session()
    token = se_get_token(requests_session)
    se_login(requests_session, token)
    events = se_parse_events(session, requests_session)
    return events

def process_events(session, events: List[Event]):
    for event in events:
        if not event.message_id:
            notify_new_event(event)
            session.commit()

engine = create_engine(f'sqlite:///{conf["db_file"]}')
Session = sessionmaker(bind=engine)

def main():
    if not isfile(conf["db_file"]):
        logger.info(f"Creating db file: ./{conf['db_file']}")
        Base.metadata.create_all(engine)
    session = Session()

    events = get_non_sent_events(session)
    if events:
        logger.debug(f"Retrying sending {len(events)} non sent events:")
        process_events(session, events)

    events = MadridDestinoGetter(session)
    process_events(session, events)

    events = SecutixScraper(session)
    process_events(session, events)

    non_sent_events = get_non_sent_events(session)
    if non_sent_events:
        logger.debug(f"There are {len(non_sent_events)} non sent events left in the database:")
        for event in non_sent_events:
            logger.debug(f"- {event}")


if __name__ == '__main__':
    main()
